CREATE TABLE readings (cookid INT,time TEXT,probe1 INT,probe2 INT);
CREATE TABLE activecook (cookid INT);
CREATE TABLE smokers (id INTEGER PRIMARY KEY AUTOINCREMENT,desc TEXT,archived INT);
CREATE TABLE cooks (id INTEGER PRIMARY KEY AUTOINCREMENT,start TEXT,end TEXT,smoker INT,pitLow INT,pitHi INT,foodLow INT,foodHi INT,note TEXT);
CREATE TABLE settings (pitLow INT,pitHigh INT,foodLow INT,foodHigh INT,tempType TEXT,pitLineColor TEXT,foodLineColor TEXT,alerts TEXT,alertLimit INT,email TEXT,emailEnabled TEXT,push TEXT,pushToken TEXT,pushUser TEXT,pushDevice TEXT,pushSub TEXT,emailTo TEXT,smtp TEXT);
CREATE TABLE alerts (cookid INT,time TEXT,type TEXT,message TEXT,read INT);
INSERT INTO activecook (cookid) VALUES (-1);
INSERT INTO settings (pitLow,pitHigh,foodLow,foodHigh,tempType,pitLineColor,foodLineColor,alerts,alertLimit,email,emailEnabled,push,pushToken,pushUser,pushDevice,pushSub,emailTo,smtp) VALUES (0,0,0,0,'F','#291A5B','#008789','off',1,'','off','off','','','','','','');
PRAGMA journal_mode=WAL;